### ISSUE TITLE
No uses assertEquals jamás :)

### ISSUE THREAD

**Issue by TavoNiievez** [jananaya/data-structures-2#4]
El 99.9% de las veces usar assertEquals es un error.
Se usa `assertSame` siempre que se pueda.

https://github.com/jananaya/data-structures-2/blob/c49010068afcd0f55210334665154940f4e84b7b/src/test/java/TADs/Trasporte/ConjuntoTrasporteTest.java#L21

**Comment by jananaya** [comment]
En los casos de prueba que escribí quiero verificar que los objetos sean idénticos, no que su dirección de memoria sea la misma.
https://www.javacodex.com/JUnit/Difference-between-assertSame-and-assertEquals

**Comment by TavoNiievez** [comment]
Interesante, en JUnit la implementación es diferente que en PHPUnit.

En PHP lo que se verifica es que el objeto contenga lo mismo y sea del mismo tipo; ej. 
```php
assertEquals("12", 12); // true
assertSame("12", 12); // false
```
